### ISSUE TITLE
No .exe file in the download

### ISSUE THREAD

**Issue by Dussi** [Maxx53/NoCableLauncher#14]
Downloaded all the files but there was no exe for the nocable launcher. the settings.bat wont work due to not having the exe there i searched through all the files but couldnt find it

**Comment by Maxx53** [comment]
Download archive with binary 
https://dl.dropboxusercontent.com/u/1288526/NoCableLauncher-m-binary.rar

**Comment by Dussi** [comment]
thanks but now when i try to launch the game its comming up with the issue that it is unable to initialize the steamAPI

**Comment by Maxx53** [comment]
What version, steam or pirated?

**Comment by Dussi** [comment]
its all good i restarted my pc. seems to be working fine with some static. thanks though you were as big help
