### ISSUE TITLE
EditSettings does not find my device

### ISSUE THREAD

**Issue by JaimeSwitch** [Maxx53/NoCableLauncher#16]
I just bought the game and figured I would be able to use NoCableLauncher along with my M-Audio FastTrack Pro instead of buying a Real Tone cable. After plugging in my FastTrack, making sure the power is on, and opening EditSettings.bat, my device isn't found as an active input device. I looked up the VID and PID in the Device Manager to set them manually. I found (VID) 0763 and (PID) 2012, but after entering those numbers and clicking "Save" I get an error "Object reference not set to an instance of an object." I'm not sure if this is an error on my part or if it is on the program, or my computer.
Attached an image to show what happened. Top left is what I found in Device Manager, right is what I entered in NoCableLauncher, and bottom left is the error dialog box.
![error](https://cloud.githubusercontent.com/assets/2581437/21570605/8ad90018-ce95-11e6-868d-7186f2cec157.png)

**Comment by Maxx53** [comment]
So, your device showed in control panel?
Just like:
![image](https://cloud.githubusercontent.com/assets/5123763/21576160/7b81fa42-cf36-11e6-8060-68ecbfad5c2c.png)

Anyway, you always can edit settings manually through settings.xml:
```
  <setting name="VID">0763</setting>
  <setting name="PID">2012</setting>
```

**Comment by JaimeSwitch** [comment]
No, it did not.
I forgot to reinstall my device drivers after upgrading my system. EditSettings.bat now finds the device after installing the proper driver. Silly user error!
