### ISSUE TITLE
Nocable & CDLC's 

### ISSUE THREAD

**Issue by Alexx7** [Maxx53/NoCableLauncher#20]
First of all, thanks for your work.

I've noticed an issue when I try to use cdlc's.
To work, cdlc's needs a "d3dx9_42.dll" files.
The problem seems to come from the interaction between the patch and the dll files.
(there is no issue if the dll file is not present.)

2 options:
-it is specified that nocable is unable to find the offcet  and later that it can't find process: Rocksmith 2014.exe
(this option is always the first to happen)
-the game crash directly

**Comment by Maxx53** [comment]
What game version, Steam or not?

**Comment by Alexx7** [comment]
not

**Comment by Maxx53** [comment]
Well, you're right, with that dll, exe needs more time to fully load in memory.
I think, promlem is my buggy process hooking
https://github.com/Maxx53/NoCableLauncher/blob/master/scr/NoCableLauncher/Program.cs#L170

Someday, i'll get pirate version with cdlc and test that issue.

**Comment by Alexx7** [comment]
Take all your time, 
I'm surely going to buy a legit version anyway, but still using your patch
