### ISSUE TITLE
Rocksmitch 2014 remastered and Behringer UMC22

### ISSUE THREAD

**Issue by Nerus87** [Maxx53/NoCableLauncher#33]
Hi,

~~I don't have any idea is this a problem with **NoCableLauncher** or **UMC22** but I can't hear guitar in the game.~~

The problem is with channel selection by Rocksmith 2014. There is any way to invert channel (left to right), e.g. change values in the memory of Rocksmith process?

**Comment by rayman1ray** [comment]
Try this https://github.com/Maxx53/NoCableLauncher/issues/35

**Comment by Nerus87** [comment]
Thx, closing issue.
