### ISSUE TITLE
Behringer U-Phoria UM2

### ISSUE THREAD

**Issue by rayman1ray** [Maxx53/NoCableLauncher#35]
Hi,

I'm trying to get the remastered edition to work with Behringer U-Phoria UM2 but I just cant.
Disable all inputs but the behringer, set it to 16bit 48k, I am using the left channel (microphone one) but still it is not not working, keeps asking for real tone cable.
I dont know what else to do to make it work, I even renamed the interface as rocksmit cable from regedit.

**Comment by Maxx53** [comment]
Hey, are you using Steam version? I think, launcher patch at wrong offset, or has no enough wait time to patch (game loads in memory to long).
Try "NoCableLauncher-m-binary-test.rar" at Release page, this version finds offsets automatically.

Unfortunately, I removed delay setting, and now to edit this value you need to rebuild the project:
https://github.com/Maxx53/NoCableLauncher/blob/master/scr/NoCableLauncher/Program.cs#L176

**Comment by rayman1ray** [comment]
Yes, I am using the steam version of the game.
Unfortunately I have no programming skills whatsoever so can you please help me with the rebuilding part?

**Comment by rayman1ray** [comment]
I got it working with the binary.test, also a side note for others; make sure steam is running when you start the game with the launcher otherwise it will still ask for the real tone cable.

**Comment by rayman1ray** [comment]
You also need to run as admin.

**Comment by t2ac32** [comment]
> I got it working with the binary.test, also a side note for others; make sure steam is running when you start the game with the launcher otherwise it will still ask for the real tone cable.

Could you explain a bit more in detail the steps you did? 
i'm about to buy a um2 interface. Does it work fine? or is the same as connecting to micrphone?

**Comment by FMGordillo** [comment]
tried to replicate the steps, installing drivers
![image](https://user-images.githubusercontent.com/7970174/99888535-591a2180-2c2c-11eb-9c80-f1399ba4ed26.png)
but nothing is working as expected. Guitar Rig takes perfectly the guitar, so idk what might be
