### ISSUE TITLE
canot configure

### ISSUE THREAD

**Issue by japrogramer** [Maxx53/NoCableLauncher#5]
hello, im trying to use this program with the steam version of rocksmith with no crack applied
in wine. when i run the bat file, nothing happens. except wine complains that the exec order was ignored. no other program does this. another strange thing is that when i launch the program for whatever reason it launches steam..

**Comment by japrogramer** [comment]
launcher crashes in wine
```
System.NotImplementedException: The method or operation is not implemented.
at NoCableLauncher.Settings.LoadDeviceList () <0x1db50c8 + 0x000d3> in <filename unknown>:0
at NoCableLauncher.Settings.Settings_Load (System.Object sender, System.EventArgs e) <0x1db23a0 + 0x00043> in <filename unknown>:0
at System.Windows.Forms.Form.OnLoad (System.EventArgs e) <0x1db21a8 + 0x00062> in <filename unknown>:0
at System.Windows.Forms.Form.OnLoadInternal (System.EventArgs e) <0x1db1f80 + 0x00078> in <filename unknown>:0

**Comment by Achtman** [comment]
Try to increase waitTime parameter in "settings.xml" file. It's time that launcher wait while game starts. Also make sure that you have steam running when you launch the bat file. Also try running it as administrator.

**Comment by japrogramer** [comment]
hello i want to try this but i don't see a settings.xml file .. in the source or in the binary
im using the binary and em unable to build from source because i em in linux. is there way to effect this setting and have the binary use the new settings?

**Comment by Achtman** [comment]
I'm not sure with the binary build I guess you will have to get the creator to answer :/. Good luck

**Comment by Maxx53** [comment]
@japrogramer hi, settings.xml will be created after first configuring (by running "EditSettings.bat" or starting EXE with "-set" parameter)

**Comment by japrogramer** [comment]
I tried for a while to change the vendor id of the cheap cable to match the id of the real-tone cable, using this and other methods. ultimately ended up buying two real tone cable about a year ago.
