### ISSUE TITLE
Patch no longer works

### ISSUE THREAD

**Issue by DeadKurt** [Maxx53/NoCableLauncher#56]
After the last update of the game, the cable does not work anymore, and the executable file of the patch does not seem to start but it starts directly from the original game.
Is there a way to update the patch?

**Comment by dgleyzer** [comment]
Not sure what problem you're experiencing but I can confirm it's working for me after installing the game yesterday.

**Comment by f3flight** [comment]
+1 no longer works after latest WIndows 10 update
UPD somehow my settings for the launcher have gone wrong, I ran EditSettings.bat and set everything up correctly, and it worked! No issues.

**Comment by DeadKurt** [comment]
Hello thanks for the replies, yes I confirm that everything works as before, it was just a problem of the Windows microphone that I had accidentally switched off.

**Comment by f3flight** [comment]
@DeadKurt don't forget to close the bug :)
