### ISSUE TITLE
Rocksmith Remastered Patch

### ISSUE THREAD

**Issue by Airtrooper719** [Maxx53/NoCableLauncher#7]
Since the remastered patch the no cable patch doesn't work. Any chance you could update it, would really appreciate it, thanks.

**Comment by Maxx53** [comment]
Solved on steam forum... Changes commited

**Comment by Last-Peacer** [comment]
Could you suggest how to put added you upgrade?

**Comment by pavko** [comment]
There are new addresses must be for Remastered (found on reddit)
<setting name="offcetVID">012C96EC</setting>
<setting name="offcetPID">012C96F4</setting>

**Comment by Last-Peacer** [comment]
This I have found, but can not find exactly where it is necessary to change, could you mnenapisat detail how to get to this point?

**Comment by DiegoDN** [comment]
@Last-Peacer the binary on project page is already with those addresses >> https://github.com/Maxx53/NoCableLauncher

**Comment by Last-Peacer** [comment]
Thank you, I tupil, in the folder where the file threw remained CML Ned upgrade program again to all of you thank you very much.

**Comment by Maxx53** [comment]
Тупил он. Ох артист...
