### ISSUE TITLE
Offcets not found

### ISSUE THREAD

**Issue by Rilord** [Maxx53/NoCableLauncher#73]
Stucked with this message. I am currently using Focusrite Solo.

**Comment by dylangovender** [comment]
I had this issue when I installed D3DX9_42.dll.

Once I removed it, the NoCableLauncher started working again.

**Comment by Sumiito1** [comment]
> I had this issue when I installed D3DX9_42.dll.
> 
> Once I removed it, the NoCableLauncher started working again.

Did your CDLCs (if you are using them) worked after removing the dll?
