### ISSUE TITLE
[Request] Integrate ASIO4All into the launcher

### ISSUE THREAD

**Issue by NikhilSaini38** [Maxx53/NoCableLauncher#74]
Please look into the possibility of adding an option of ASIO mode into the launcher. I believe it would allow multiplayer mode from the same USB audio interface and hence would be useful with this launcher, along with buffer size management. I have a Behringer interface with 2 inputs. I will also go through the code and see where I can be any help.

[here](https://github.com/mdias/rs_asio) is another dev's attempt at it, if it is any help to start.

**Comment by Maxx53** [comment]
rs_asio is ultimate solution for your needs. it perfectly works with multiplayer from one device.
